spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tx-manager?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 172.23.148.54
    port: 6379
    password: 123456
  application:
    name: tx-manager
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect  # 数据库方言
    hibernate.ddl-auto: create  #第一次运行可以设置为: create, 为TM创建持久化数据库表

eureka:
  instance:
    hostname: 127.0.0.1
    #修改eureka-client在注册中心页面显示的名字
    #${spring.cloud.client.ipaddress} 获取服务的ip地址
    instance-id: stock-txManager-${spring.cloud.client.ipaddress}-${server.port}
    #服务信息显示的真实的ip, 开发中一定要设置为true, 如果不设置, 其他电脑访问不到你的服务
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
tx-lcn:
  manager:
    host: 127.0.0.1 # tx-manager ip(client请求ip)
    port: 8070  # client 请求端口
    heart-time: 12000 # 心跳检测时间 单位：ms
    dtx-time: 30000 # 事务执行总时间
    admin-key: 123456 #TM后台登陆密码,默认密码是codingapi
  logger:
    enabled: true #开启日志,默认为false,开发阶段最好开启日志，并设置为debug等级，这样方便追踪排查问题
    #日志记录表 t_logger
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    only-error: false
tm:
  compensate:
    noti
logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG  #日志输出级别
server:
  port: 7970